# Astro Dozi — Codemagic CI/CD Configuration
# Docs: https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/

workflows:
  # ============================================================
  # iOS Test Build (code signing yok, sadece derleme testi)
  # ============================================================
  ios-test:
    name: iOS Test Build (No Signing)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials      # GOOGLE_SERVICE_INFO_PLIST (base64), GEMINI_API_KEY

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods

    scripts:
      - name: Create .env file
        script: |
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" > $CM_BUILD_DIR/.env

      - name: Set up Firebase iOS config
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
          echo "GoogleService-Info.plist size: $(wc -c < $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist) bytes"
          grep GOOGLE_APP_ID $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist || echo "WARNING: GOOGLE_APP_ID not found in plist!"

      - name: Generate firebase_options.dart
        script: |
          cat > $CM_BUILD_DIR/lib/firebase_options.dart << 'EOF'
          import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
          import 'package:flutter/foundation.dart'
              show defaultTargetPlatform, kIsWeb, TargetPlatform;

          class DefaultFirebaseOptions {
            static FirebaseOptions get currentPlatform {
              if (kIsWeb) {
                throw UnsupportedError('Web is not supported.');
              }
              switch (defaultTargetPlatform) {
                case TargetPlatform.android:
                  return android;
                case TargetPlatform.iOS:
                  return ios;
                default:
                  throw UnsupportedError(
                    'DefaultFirebaseOptions are not supported for this platform.',
                  );
              }
            }

            static const FirebaseOptions android = FirebaseOptions(
              apiKey: 'AIzaSyBzRqWacN-ba8IouBuomcMg5Ubf7XObrn8',
              appId: '1:810852009885:android:368a6700c9860bb784d174',
              messagingSenderId: '810852009885',
              projectId: 'zodi-cf6b7',
              storageBucket: 'zodi-cf6b7.firebasestorage.app',
            );

            static const FirebaseOptions ios = FirebaseOptions(
              apiKey: 'AIzaSyByqtbMonl7tGCZTzVU3GLrH8nSXucSm4A',
              appId: '1:810852009885:ios:f78b53ca5ce6354584d174',
              messagingSenderId: '810852009885',
              projectId: 'zodi-cf6b7',
              storageBucket: 'zodi-cf6b7.firebasestorage.app',
              iosBundleId: 'com.bardino.zodi',
            );
          }
          EOF
          echo "firebase_options.dart generated:"
          cat $CM_BUILD_DIR/lib/firebase_options.dart

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR/ios && pod install --repo-update

      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - astrodozi@dozi.app
        notify:
          success: true
          failure: true

  # ============================================================
  # iOS Release → TestFlight
  # ============================================================
  ios-release:
    name: iOS Release (TestFlight)
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Astro Dozi ASC Key

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials      # GOOGLE_SERVICE_INFO_PLIST (base64), GEMINI_API_KEY, CERTIFICATE_PRIVATE_KEY

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*-ios'
          include: true
        - pattern: 'v*'
          include: true

    scripts:
      - name: Set up code signing
        script: |
          # Fetch or create signing files from Apple Developer Portal
          app-store-connect fetch-signing-files "com.bardino.zodi" \
            --type IOS_APP_STORE \
            --create
          # Initialize keychain and add certificates
          keychain initialize
          keychain add-certificates
          # Apply profiles to Xcode project
          xcode-project use-profiles

      - name: Create .env file
        script: |
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" > $CM_BUILD_DIR/.env

      - name: Set up Firebase iOS config
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
          echo "GoogleService-Info.plist size: $(wc -c < $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist) bytes"
          grep GOOGLE_APP_ID $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist || echo "WARNING: GOOGLE_APP_ID not found in plist!"

      - name: Generate firebase_options.dart
        script: |
          cat > $CM_BUILD_DIR/lib/firebase_options.dart << 'EOF'
          import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
          import 'package:flutter/foundation.dart'
              show defaultTargetPlatform, kIsWeb, TargetPlatform;

          class DefaultFirebaseOptions {
            static FirebaseOptions get currentPlatform {
              if (kIsWeb) {
                throw UnsupportedError('Web is not supported.');
              }
              switch (defaultTargetPlatform) {
                case TargetPlatform.android:
                  return android;
                case TargetPlatform.iOS:
                  return ios;
                default:
                  throw UnsupportedError(
                    'DefaultFirebaseOptions are not supported for this platform.',
                  );
              }
            }

            static const FirebaseOptions android = FirebaseOptions(
              apiKey: 'AIzaSyBzRqWacN-ba8IouBuomcMg5Ubf7XObrn8',
              appId: '1:810852009885:android:368a6700c9860bb784d174',
              messagingSenderId: '810852009885',
              projectId: 'zodi-cf6b7',
              storageBucket: 'zodi-cf6b7.firebasestorage.app',
            );

            static const FirebaseOptions ios = FirebaseOptions(
              apiKey: 'AIzaSyByqtbMonl7tGCZTzVU3GLrH8nSXucSm4A',
              appId: '1:810852009885:ios:f78b53ca5ce6354584d174',
              messagingSenderId: '810852009885',
              projectId: 'zodi-cf6b7',
              storageBucket: 'zodi-cf6b7.firebasestorage.app',
              iosBundleId: 'com.bardino.zodi',
            );
          }
          EOF
          echo "firebase_options.dart generated:"
          cat $CM_BUILD_DIR/lib/firebase_options.dart

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR/ios && pod install --repo-update

      - name: Build IPA
        script: |
          # Get latest build number from App Store Connect (includes all statuses)
          LATEST=$(app-store-connect get-latest-build-number "com.bardino.zodi" 2>/dev/null || echo "0")
          if [ -z "$LATEST" ] || [ "$LATEST" = "None" ] || [ "$LATEST" -lt 1 ] 2>/dev/null; then
            LATEST=0
          fi
          # Also check TestFlight specifically
          TF_LATEST=$(app-store-connect get-latest-testflight-build-number "com.bardino.zodi" 2>/dev/null || echo "0")
          if [ -z "$TF_LATEST" ] || [ "$TF_LATEST" = "None" ]; then
            TF_LATEST=0
          fi
          # Use whichever is higher
          if [ "$TF_LATEST" -gt "$LATEST" ] 2>/dev/null; then
            LATEST=$TF_LATEST
          fi
          # Absolute minimum fallback
          if [ "$LATEST" -lt 18 ]; then
            LATEST=18
          fi
          BUILD_NUMBER=$((LATEST + 1))
          echo "=== Build Number Resolution ==="
          echo "App Store latest: $LATEST"
          echo "TestFlight latest: $TF_LATEST"
          echo "Final build number: $BUILD_NUMBER"
          echo "==============================="
          flutter build ipa --release \
            --build-name=1.0.1 \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - astrodozi@dozi.app
        notify:
          success: true
          failure: true

  # ============================================================
  # Android Release → Play Store (Internal Testing)
  # ============================================================
  android-release:
    name: Android Release (Play Store)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      groups:
        - android_credentials
      android_signing:
        - astro_dozi_keystore

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*-android'
          include: true
        - pattern: 'v*'
          include: true

    scripts:
      - name: Create .env file
        script: |
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" > $CM_BUILD_DIR/.env

      - name: Generate firebase_options.dart
        script: |
          cat > $CM_BUILD_DIR/lib/firebase_options.dart << 'EOF'
          import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
          import 'package:flutter/foundation.dart'
              show defaultTargetPlatform, kIsWeb, TargetPlatform;

          class DefaultFirebaseOptions {
            static FirebaseOptions get currentPlatform {
              if (kIsWeb) {
                throw UnsupportedError('Web is not supported.');
              }
              switch (defaultTargetPlatform) {
                case TargetPlatform.android:
                  return android;
                case TargetPlatform.iOS:
                  return ios;
                default:
                  throw UnsupportedError(
                    'DefaultFirebaseOptions are not supported for this platform.',
                  );
              }
            }

            static const FirebaseOptions android = FirebaseOptions(
              apiKey: 'AIzaSyBzRqWacN-ba8IouBuomcMg5Ubf7XObrn8',
              appId: '1:810852009885:android:368a6700c9860bb784d174',
              messagingSenderId: '810852009885',
              projectId: 'zodi-cf6b7',
              storageBucket: 'zodi-cf6b7.firebasestorage.app',
            );

            static const FirebaseOptions ios = FirebaseOptions(
              apiKey: 'AIzaSyByqtbMonl7tGCZTzVU3GLrH8nSXucSm4A',
              appId: '1:810852009885:ios:f78b53ca5ce6354584d174',
              messagingSenderId: '810852009885',
              projectId: 'zodi-cf6b7',
              storageBucket: 'zodi-cf6b7.firebasestorage.app',
              iosBundleId: 'com.bardino.zodi',
            );
          }
          EOF

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
      email:
        recipients:
          - astrodozi@dozi.app
        notify:
          success: true
          failure: true
