# Astro Dozi — Codemagic CI/CD Configuration
# Docs: https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/

workflows:
  # ============================================================
  # iOS Test Build (code signing yok, sadece derleme testi)
  # ============================================================
  ios-test:
    name: iOS Test Build (No Signing)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials      # GOOGLE_SERVICE_INFO_PLIST (base64), GEMINI_API_KEY

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods

    scripts:
      - name: Create .env file
        script: |
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" > $CM_BUILD_DIR/.env

      - name: Set up Firebase iOS config
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR/ios && pod install --repo-update

      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - info@dozi.app
        notify:
          success: true
          failure: true

  # ============================================================
  # iOS Release → TestFlight
  # ============================================================
  ios-release:
    name: iOS Release (TestFlight)
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Astro Dozi ASC Key

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.bardino.zodi
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: "com.bardino.zodi"

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*-ios'
          include: true
        - pattern: 'v*'
          include: true

    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Create .env file
        script: |
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" > $CM_BUILD_DIR/.env

      - name: Set up Firebase iOS config
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR/ios && pod install --repo-update

      - name: Set build number
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$APP_ID" || echo 0)
          BUILD_NUMBER=$((LATEST_BUILD + 1))
          echo "Building version 1.0.0+$BUILD_NUMBER"

      - name: Build IPA
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$APP_ID" || echo 0)
          BUILD_NUMBER=$((LATEST_BUILD + 1))
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - info@dozi.app
        notify:
          success: true
          failure: true

  # ============================================================
  # Android Release → Play Store (Internal Testing)
  # ============================================================
  android-release:
    name: Android Release (Play Store)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      groups:
        - android_credentials
      android_signing:
        - astro_dozi_keystore

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*-android'
          include: true
        - pattern: 'v*'
          include: true

    scripts:
      - name: Create .env file
        script: |
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" > $CM_BUILD_DIR/.env

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
      email:
        recipients:
          - info@dozi.app
        notify:
          success: true
          failure: true
