import '../models/tarot_card.dart';

// 78 Tarot kartının tam listesi
class TarotData {
  static final List<Map<String, dynamic>> allCards = [
    // Major Arcana (0-21)
    {
      'name': 'Deli',
      'number': 0,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Yeni başlangıçlar, spontanlık, masumiyet, özgürlük',
    },
    {
      'name': 'Büyücü',
      'number': 1,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Güç, beceri, konsantrasyon, eylem',
    },
    {
      'name': 'Azize',
      'number': 2,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Sezgi, bilinçaltı, gizem, bilgelik',
    },
    {
      'name': 'İmparatoriçe',
      'number': 3,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Bereket, doğa, yaratıcılık, bolluk',
    },
    {
      'name': 'İmparator',
      'number': 4,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Otorite, yapı, kontrol, liderlik',
    },
    {
      'name': 'Aziz',
      'number': 5,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Gelenek, konformizm, eğitim, inanç',
    },
    {
      'name': 'Aşıklar',
      'number': 6,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Aşk, uyum, ilişkiler, seçimler',
    },
    {
      'name': 'Savaş Arabası',
      'number': 7,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Kontrol, irade gücü, zafer, kararlılık',
    },
    {
      'name': 'Güç',
      'number': 8,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Cesaret, sabır, kontrol, şefkat',
    },
    {
      'name': 'Ermiş',
      'number': 9,
      'suit': TarotSuit.majorArcana,
      'meaning': 'İçe dönüş, yalnızlık, rehberlik, bilgelik',
    },
    {
      'name': 'Kader Çarkı',
      'number': 10,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Kader, döngüler, dönüm noktaları, şans',
    },
    {
      'name': 'Adalet',
      'number': 11,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Adalet, denge, gerçek, sebep-sonuç',
    },
    {
      'name': 'Asılan Adam',
      'number': 12,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Fedakarlık, bekleme, yeni bakış açısı',
    },
    {
      'name': 'Ölüm',
      'number': 13,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Dönüşüm, son, yeni başlangıç, değişim',
    },
    {
      'name': 'Denge',
      'number': 14,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Denge, ılımlılık, sabır, uyum',
    },
    {
      'name': 'Şeytan',
      'number': 15,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Bağımlılık, kısıtlama, materyalizm',
    },
    {
      'name': 'Kule',
      'number': 16,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Ani değişim, kaos, aydınlanma, yıkım',
    },
    {
      'name': 'Yıldız',
      'number': 17,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Umut, ilham, yenilenme, iyileşme',
    },
    {
      'name': 'Ay',
      'number': 18,
      'suit': TarotSuit.majorArcana,
      'meaning': 'İllüzyon, korku, bilinçaltı, sezgi',
    },
    {
      'name': 'Güneş',
      'number': 19,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Başarı, mutluluk, canlılık, pozitiflik',
    },
    {
      'name': 'Mahkeme',
      'number': 20,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Yargı, yeniden doğuş, iç ses, bağışlama',
    },
    {
      'name': 'Dünya',
      'number': 21,
      'suit': TarotSuit.majorArcana,
      'meaning': 'Tamamlanma, başarı, yolculuk sonu',
    },

    // Wands (Asalar) - 1-14
    {
      'name': 'Asaların Ası',
      'number': 1,
      'suit': TarotSuit.wands,
      'meaning': 'Yaratıcılık, ilham, yeni fırsatlar',
    },
    {
      'name': 'Asaların İkilisi',
      'number': 2,
      'suit': TarotSuit.wands,
      'meaning': 'Planlama, kararlar, keşif',
    },
    {
      'name': 'Asaların Üçlüsü',
      'number': 3,
      'suit': TarotSuit.wands,
      'meaning': 'Genişleme, öngörü, liderlik',
    },
    {
      'name': 'Asaların Dörtlüsü',
      'number': 4,
      'suit': TarotSuit.wands,
      'meaning': 'Kutlama, uyum, ev, topluluk',
    },
    {
      'name': 'Asaların Beşlisi',
      'number': 5,
      'suit': TarotSuit.wands,
      'meaning': 'Çatışma, rekabet, anlaşmazlık',
    },
    {
      'name': 'Asaların Altılısı',
      'number': 6,
      'suit': TarotSuit.wands,
      'meaning': 'Zafer, tanınma, başarı',
    },
    {
      'name': 'Asaların Yedilisi',
      'number': 7,
      'suit': TarotSuit.wands,
      'meaning': 'Meydan okuma, rekabet, kararlılık',
    },
    {
      'name': 'Asaların Sekizlisi',
      'number': 8,
      'suit': TarotSuit.wands,
      'meaning': 'Hız, hareket, heyecan',
    },
    {
      'name': 'Asaların Dokuzlusu',
      'number': 9,
      'suit': TarotSuit.wands,
      'meaning': 'Dayanıklılık, sebat, savunma',
    },
    {
      'name': 'Asaların Onlusu',
      'number': 10,
      'suit': TarotSuit.wands,
      'meaning': 'Yük, sorumluluk, stres',
    },
    {
      'name': 'Asaların Prensi',
      'number': 11,
      'suit': TarotSuit.wands,
      'meaning': 'Heyecan, macera, enerji',
    },
    {
      'name': 'Asaların Şövalyesi',
      'number': 12,
      'suit': TarotSuit.wands,
      'meaning': 'Tutku, eylem, macera',
    },
    {
      'name': 'Asaların Kraliçesi',
      'number': 13,
      'suit': TarotSuit.wands,
      'meaning': 'Cesaret, özgüven, kararlılık',
    },
    {
      'name': 'Asaların Kralı',
      'number': 14,
      'suit': TarotSuit.wands,
      'meaning': 'Vizyon, girişimcilik, liderlik',
    },

    // Cups (Kadehler) - 1-14
    {
      'name': 'Kadehlerin Ası',
      'number': 1,
      'suit': TarotSuit.cups,
      'meaning': 'Aşk, yeni ilişkiler, şefkat',
    },
    {
      'name': 'Kadehlerin İkilisi',
      'number': 2,
      'suit': TarotSuit.cups,
      'meaning': 'Ortaklık, birlik, bağlantı',
    },
    {
      'name': 'Kadehlerin Üçlüsü',
      'number': 3,
      'suit': TarotSuit.cups,
      'meaning': 'Kutlama, arkadaşlık, yaratıcılık',
    },
    {
      'name': 'Kadehlerin Dörtlüsü',
      'number': 4,
      'suit': TarotSuit.cups,
      'meaning': 'Meditasyon, yeniden değerlendirme',
    },
    {
      'name': 'Kadehlerin Beşlisi',
      'number': 5,
      'suit': TarotSuit.cups,
      'meaning': 'Kayıp, pişmanlık, hayal kırıklığı',
    },
    {
      'name': 'Kadehlerin Altılısı',
      'number': 6,
      'suit': TarotSuit.cups,
      'meaning': 'Nostalji, anılar, masumiyet',
    },
    {
      'name': 'Kadehlerin Yedilisi',
      'number': 7,
      'suit': TarotSuit.cups,
      'meaning': 'Seçenekler, hayaller, illüzyon',
    },
    {
      'name': 'Kadehlerin Sekizlisi',
      'number': 8,
      'suit': TarotSuit.cups,
      'meaning': 'Ayrılık, geçiş, arama',
    },
    {
      'name': 'Kadehlerin Dokuzlusu',
      'number': 9,
      'suit': TarotSuit.cups,
      'meaning': 'Memnuniyet, mutluluk, tatmin',
    },
    {
      'name': 'Kadehlerin Onlusu',
      'number': 10,
      'suit': TarotSuit.cups,
      'meaning': 'Uyum, mutluluk, aile',
    },
    {
      'name': 'Kadehlerin Prensi',
      'number': 11,
      'suit': TarotSuit.cups,
      'meaning': 'Yaratıcılık, sezgi, romantizm',
    },
    {
      'name': 'Kadehlerin Şövalyesi',
      'number': 12,
      'suit': TarotSuit.cups,
      'meaning': 'Romantizm, şarm, hayal',
    },
    {
      'name': 'Kadehlerin Kraliçesi',
      'number': 13,
      'suit': TarotSuit.cups,
      'meaning': 'Şefkat, sakinlik, sezgi',
    },
    {
      'name': 'Kadehlerin Kralı',
      'number': 14,
      'suit': TarotSuit.cups,
      'meaning': 'Duygusal denge, diplomasi',
    },

    // Swords (Kılıçlar) - 1-14
    {
      'name': 'Kılıçların Ası',
      'number': 1,
      'suit': TarotSuit.swords,
      'meaning': 'Netlik, gerçek, zihinsel güç',
    },
    {
      'name': 'Kılıçların İkilisi',
      'number': 2,
      'suit': TarotSuit.swords,
      'meaning': 'Karar, ikilem, denge',
    },
    {
      'name': 'Kılıçların Üçlüsü',
      'number': 3,
      'suit': TarotSuit.swords,
      'meaning': 'Kalp kırıklığı, acı, kayıp',
    },
    {
      'name': 'Kılıçların Dörtlüsü',
      'number': 4,
      'suit': TarotSuit.swords,
      'meaning': 'Dinlenme, iyileşme, meditasyon',
    },
    {
      'name': 'Kılıçların Beşlisi',
      'number': 5,
      'suit': TarotSuit.swords,
      'meaning': 'Çatışma, kayıp, yenilgi',
    },
    {
      'name': 'Kılıçların Altılısı',
      'number': 6,
      'suit': TarotSuit.swords,
      'meaning': 'Geçiş, değişim, seyahat',
    },
    {
      'name': 'Kılıçların Yedilisi',
      'number': 7,
      'suit': TarotSuit.swords,
      'meaning': 'Hile, strateji, dikkat',
    },
    {
      'name': 'Kılıçların Sekizlisi',
      'number': 8,
      'suit': TarotSuit.swords,
      'meaning': 'Kısıtlama, sıkışmışlık, korku',
    },
    {
      'name': 'Kılıçların Dokuzlusu',
      'number': 9,
      'suit': TarotSuit.swords,
      'meaning': 'Endişe, korku, kabus',
    },
    {
      'name': 'Kılıçların Onlusu',
      'number': 10,
      'suit': TarotSuit.swords,
      'meaning': 'Son, dönüşüm, yeni başlangıç',
    },
    {
      'name': 'Kılıçların Prensi',
      'number': 11,
      'suit': TarotSuit.swords,
      'meaning': 'Merak, enerji, hızlılık',
    },
    {
      'name': 'Kılıçların Şövalyesi',
      'number': 12,
      'suit': TarotSuit.swords,
      'meaning': 'Hırs, eylem, dürtü',
    },
    {
      'name': 'Kılıçların Kraliçesi',
      'number': 13,
      'suit': TarotSuit.swords,
      'meaning': 'Bağımsızlık, netlik, doğrudan',
    },
    {
      'name': 'Kılıçların Kralı',
      'number': 14,
      'suit': TarotSuit.swords,
      'meaning': 'Otorite, gerçek, etik',
    },

    // Pentacles (Tılsımlar) - 1-14
    {
      'name': 'Tılsımların Ası',
      'number': 1,
      'suit': TarotSuit.pentacles,
      'meaning': 'Fırsat, bolluk, yeni girişim',
    },
    {
      'name': 'Tılsımların İkilisi',
      'number': 2,
      'suit': TarotSuit.pentacles,
      'meaning': 'Denge, uyum, zaman yönetimi',
    },
    {
      'name': 'Tılsımların Üçlüsü',
      'number': 3,
      'suit': TarotSuit.pentacles,
      'meaning': 'İşbirliği, öğrenme, uzmanlık',
    },
    {
      'name': 'Tılsımların Dörtlüsü',
      'number': 4,
      'suit': TarotSuit.pentacles,
      'meaning': 'Güvenlik, kontrol, koruma',
    },
    {
      'name': 'Tılsımların Beşlisi',
      'number': 5,
      'suit': TarotSuit.pentacles,
      'meaning': 'Zorluk, kayıp, yoksulluk',
    },
    {
      'name': 'Tılsımların Altılısı',
      'number': 6,
      'suit': TarotSuit.pentacles,
      'meaning': 'Cömertlik, paylaşım, denge',
    },
    {
      'name': 'Tılsımların Yedilisi',
      'number': 7,
      'suit': TarotSuit.pentacles,
      'meaning': 'Sabır, uzun vadeli vizyon',
    },
    {
      'name': 'Tılsımların Sekizlisi',
      'number': 8,
      'suit': TarotSuit.pentacles,
      'meaning': 'Ustalık, beceri, çalışkanlık',
    },
    {
      'name': 'Tılsımların Dokuzlusu',
      'number': 9,
      'suit': TarotSuit.pentacles,
      'meaning': 'Bolluk, lüks, bağımsızlık',
    },
    {
      'name': 'Tılsımların Onlusu',
      'number': 10,
      'suit': TarotSuit.pentacles,
      'meaning': 'Zenginlik, miras, aile',
    },
    {
      'name': 'Tılsımların Prensi',
      'number': 11,
      'suit': TarotSuit.pentacles,
      'meaning': 'Hırs, hedefler, pratiklik',
    },
    {
      'name': 'Tılsımların Şövalyesi',
      'number': 12,
      'suit': TarotSuit.pentacles,
      'meaning': 'Verimlilik, rutin, güvenilirlik',
    },
    {
      'name': 'Tılsımların Kraliçesi',
      'number': 13,
      'suit': TarotSuit.pentacles,
      'meaning': 'Pratiklik, konfor, güvenlik',
    },
    {
      'name': 'Tılsımların Kralı',
      'number': 14,
      'suit': TarotSuit.pentacles,
      'meaning': 'Bolluk, güvenlik, liderlik',
    },
  ];

  static TarotCard getCard(int index, bool reversed) {
    final cardData = allCards[index];
    final cardNumber = cardData['number'] as int;
    return TarotCard(
      name: cardData['name'] as String,
      number: cardNumber,
      suit: cardData['suit'] as TarotSuit,
      reversed: reversed,
      imageUrl: 'assets/tarot/$cardNumber.webp', // cardNumber kullan (0-21 Major Arcana)
      basicMeaning: cardData['meaning'] as String,
    );
  }
  
  // İngilizce kart isimleri (AI generation için)
  static final List<String> englishNames = [
    // Major Arcana (0-21)
    'The Fool',
    'The Magician',
    'The High Priestess',
    'The Empress',
    'The Emperor',
    'The Hierophant',
    'The Lovers',
    'The Chariot',
    'Strength',
    'The Hermit',
    'Wheel of Fortune',
    'Justice',
    'The Hanged Man',
    'Death',
    'Temperance',
    'The Devil',
    'The Tower',
    'The Star',
    'The Moon',
    'The Sun',
    'Judgement',
    'The World',
    // Wands (22-35)
    'Ace of Wands',
    'Two of Wands',
    'Three of Wands',
    'Four of Wands',
    'Five of Wands',
    'Six of Wands',
    'Seven of Wands',
    'Eight of Wands',
    'Nine of Wands',
    'Ten of Wands',
    'Page of Wands',
    'Knight of Wands',
    'Queen of Wands',
    'King of Wands',
    // Cups (36-49)
    'Ace of Cups',
    'Two of Cups',
    'Three of Cups',
    'Four of Cups',
    'Five of Cups',
    'Six of Cups',
    'Seven of Cups',
    'Eight of Cups',
    'Nine of Cups',
    'Ten of Cups',
    'Page of Cups',
    'Knight of Cups',
    'Queen of Cups',
    'King of Cups',
    // Swords (50-63)
    'Ace of Swords',
    'Two of Swords',
    'Three of Swords',
    'Four of Swords',
    'Five of Swords',
    'Six of Swords',
    'Seven of Swords',
    'Eight of Swords',
    'Nine of Swords',
    'Ten of Swords',
    'Page of Swords',
    'Knight of Swords',
    'Queen of Swords',
    'King of Swords',
    // Pentacles (64-77)
    'Ace of Pentacles',
    'Two of Pentacles',
    'Three of Pentacles',
    'Four of Pentacles',
    'Five of Pentacles',
    'Six of Pentacles',
    'Seven of Pentacles',
    'Eight of Pentacles',
    'Nine of Pentacles',
    'Ten of Pentacles',
    'Page of Pentacles',
    'Knight of Pentacles',
    'Queen of Pentacles',
    'King of Pentacles',
  ];
}
